apiVersion: v1
kind: DeploymentConfig
metadata:
  name: redmine-sample
spec:
  template:
    metadata:
      labels:
        name: redmine-sample
    spec:
      containers:
      - name: redmine-latest
        image: redmine:latest
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: REDMINE_DB_MYSQL
          value: mysql-sample
          #value: mysql-sample-2-moe4j
        - name: REDMINE_DB_PASSWORD
          value: example
  replicas: 1
  selector:
    name: redmine-sample
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - redmine-sample-latest
      from:
        kind: ImageStreamTag
        name: redmine:latest
  - type: ConfigChange
